const WORDS = [
  { word: "ELEPHANT", hint: "The largest land animal on Earth" },
  { word: "PYTHON", hint: "A programming language named after a snake" },
  { word: "GUITAR", hint: "A string instrument with six strings" },
  { word: "PYRAMID", hint: "Ancient Egyptian tombs built of stone" },
  { word: "JUPITER", hint: "The largest planet in our solar system" },
  { word: "DIAMOND", hint: "The hardest natural substance on Earth" },
  { word: "PIRATE", hint: "A sea robber who attacks ships" },
  { word: "DRAGON", hint: "A mythical fire-breathing creature" },
  { word: "PIANO", hint: "A musical instrument with black and white keys" },
  { word: "VOLCANO", hint: "A mountain that erupts with lava" },
  { word: "BUTTERFLY", hint: "An insect with colorful wings" },
  { word: "CAFETERIA", hint: "A place where you buy and eat meals at school" },
  { word: "KANGAROO", hint: "An Australian animal that hops and carries babies in a pouch" },
  { word: "CHOCOLATE", hint: "A sweet treat made from cocoa beans" },
  { word: "ASTRONAUT", hint: "A person who travels to space" },
  { word: "HARMONY", hint: "When musical notes sound pleasing together" },
  { word: "BICYCLE", hint: "A vehicle with two wheels you pedal" },
  { word: "UMBRELLA", hint: "You hold this over your head when it rains" },
  { word: "GALAXY", hint: "A huge system of stars, gas, and dust" },
  { word: "JOURNAL", hint: "A book where you write your daily thoughts" },
  { word: "LANTERN", hint: "A portable light source with a protective case" },
  { word: "MYSTERY", hint: "Something that is unknown or puzzling" },
  { word: "NECKLACE", hint: "Jewelry worn around the neck" },
  { word: "ORCHESTRA", hint: "A large group of musicians playing together" },
  { word: "PARACHUTE", hint: "A device that helps you fall safely from the sky" },
  { word: "RAINBOW", hint: "A colorful arc in the sky after rain" },
  { word: "SANDWICH", hint: "Two slices of bread with filling in between" },
  { word: "TELESCOPE", hint: "An instrument used to see distant objects in space" },
  { word: "VACATION", hint: "A break from work or school for travel or rest" },
  { word: "WHISTLE", hint: "A device that makes a high-pitched sound when you blow it" },
  { word: "ALBATROSS", hint: "A large seabird with the longest wingspan" },
  { word: "BUNGALOW", hint: "A small one-story house" },
  { word: "CROCODILE", hint: "A large reptile with a long snout found in rivers" },
  { word: "DOLPHIN", hint: "A highly intelligent marine mammal" },
  { word: "ESPRESSO", hint: "A strong coffee made by forcing steam through grounds" },
  { word: "FLAMINGO", hint: "A pink bird that stands on one leg" },
  { word: "GORILLA", hint: "The largest living primate" },
  { word: "HURRICANE", hint: "A powerful tropical storm with strong winds" },
  { word: "IGLOO", hint: "A shelter made of snow blocks" },
  { word: "JELLYFISH", hint: "A gelatinous sea creature with tentacles" },
  { word: "KOALA", hint: "An Australian tree-dwelling marsupial that eats eucalyptus" },
  { word: "LEOPARD", hint: "A big cat with spots" },
  { word: "MOUNTAIN", hint: "A very tall natural elevation of the earth's surface" },
  { word: "NIGHTINGALE", hint: "A small bird known for its beautiful song" },
  { word: "OCTOPUS", hint: "A sea creature with eight arms" },
  { word: "PANDA", hint: "A black and white bear from China" },
  { word: "QUARTZ", hint: "A hard mineral often used in watches" },
  { word: "ROBOT", hint: "A machine that can perform tasks automatically" },
  { word: "SATELLITE", hint: "An object that orbits a planet" },
  { word: "TSUNAMI", hint: "A giant wave caused by an underwater earthquake" },
  { word: "UNICORN", hint: "A mythical horse with a single horn" },
  { word: "VIOLIN", hint: "A small string instrument played with a bow" },
  { word: "WALRUS", hint: "A large Arctic sea mammal with tusks" },
  { word: "XYLOPHONE", hint: "A musical instrument with wooden bars struck by mallets" },
  { word: "YACHT", hint: "A medium-sized sailing boat" },
  { word: "ZEBRA", hint: "An African animal with black and white stripes" },
  { word: "AVALANCHE", hint: "A rapid flow of snow down a mountain" },
  { word: "BASKETBALL", hint: "A sport played with a hoop and a bouncing ball" },
  { word: "CAMEL", hint: "A desert animal with humps" },
  { word: "DINOSAUR", hint: "A prehistoric reptile that went extinct" },
  { word: "ECHO", hint: "A sound that repeats when it bounces off a surface" },
  { word: "FOSSIL", hint: "The preserved remains of ancient life" },
  { word: "GLACIER", hint: "A large mass of ice that moves slowly" },
  { word: "HAIRCUT", hint: "What you get when you visit a barber or stylist" },
  { word: "ISLAND", hint: "A piece of land surrounded by water" },
  { word: "JUNGLE", hint: "A dense tropical forest" },
  { word: "KETCHUP", hint: "A tomato-based condiment" },
  { word: "LIGHTNING", hint: "A sudden electrical discharge in the sky" },
  { word: "MOSQUITO", hint: "A small flying insect that bites and sucks blood" },
  { word: "NOODLE", hint: "A long thin strip of pasta" },
  { word: "OLYMPIC", hint: "An international sports competition held every four years" },
  { word: "PENGUIN", hint: "A flightless bird that lives in Antarctica" },
  { word: "QUESTION", hint: "A sentence that asks for information" },
  { word: "RACCOON", hint: "A nocturnal mammal with a masked face" },
  { word: "SAFARI", hint: "An expedition to observe wild animals in their habitat" },
  { word: "TORNADO", hint: "A violently rotating column of air" },
  { word: "UKULELE", hint: "A small four-stringed Hawaiian instrument" },
  { word: "VAMPIRE", hint: "A mythical creature that drinks blood" },
  { word: "WATERFALL", hint: "Water flowing over a vertical drop" },
  { word: "ADVENTURE", hint: "An exciting or unusual experience" },
  { word: "BALLOON", hint: "A flexible bag filled with gas that can float" },
  { word: "CANDLE", hint: "A wax cylinder with a wick that burns to give light" },
  { word: "DESSERT", hint: "A sweet course eaten at the end of a meal" },
  { word: "ENVELOPE", hint: "A flat paper container for a letter" },
  { word: "FIREPLACE", hint: "A structure designed to contain a fire for heating" },
  { word: "GINGERBREAD", hint: "A sweet cake flavored with ginger, often shaped like a person" },
  { word: "HAMBURGER", hint: "A sandwich with a grilled patty between buns" },
  { word: "INVENTION", hint: "A new device or process created by someone" },
  { word: "JEWELRY", hint: "Decorative items worn on the body" },
  { word: "KITCHEN", hint: "A room used for cooking and preparing food" },
  { word: "LIBRARY", hint: "A building or room full of books" },
  { word: "MUSHROOM", hint: "A fungus that grows in damp places, often used in cooking" },
  { word: "NUTCRACKER", hint: "A tool used to crack open nutshells" },
  { word: "ORIGAMI", hint: "The Japanese art of paper folding" },
  { word: "POPCORN", hint: "A snack made from heated corn kernels that pop" },
  { word: "RESTAURANT", hint: "A place where meals are prepared and served to customers" },
  { word: "SKELETON", hint: "The internal framework of bones in a body" },
  { word: "TATTOO", hint: "A permanent design marked on the skin" },
  { word: "UTENSIL", hint: "A tool used in the kitchen for eating or cooking" },
  { word: "VEGETABLE", hint: "A plant or part of a plant used as food" },
  { word: "WINDMILL", hint: "A structure with blades that uses wind power" },
  { word: "BROCOLLI", hint: "A green vegetable with a thick stalk and small florets" },
  { word: "CHANDELIER", hint: "A decorative ceiling-mounted light fixture" },
  { word: "DWARF", hint: "A mythical creature that is small and lives underground" },
  { word: "FALCON", hint: "A bird of prey known for its speed" },
  { word: "GNOME", hint: "A small mythical creature that guards treasure" },
  { word: "HYENA", hint: "A wild African animal that laughs" },
  { word: "JASMINE", hint: "A fragrant white flower" },
  { word: "LOBSTER", hint: "A marine crustacean with large claws" },
  { word: "MANDOLIN", hint: "A stringed musical instrument with a teardrop shape" },
  { word: "OPERA", hint: "A dramatic performance set to music" },
  { word: "PEACOCK", hint: "A bird with a large colorful tail it can fan out" },
  { word: "SCARECROW", hint: "A decoy figure placed in fields to scare birds away" },
  { word: "TOASTER", hint: "An appliance used to brown bread" },
  { word: "VOLCANO", hint: "A mountain that can erupt with lava and ash" },
  { word: "WAFFLE", hint: "A patterned batter cake cooked in a special iron" },
  { word: "BAMBOO", hint: "A fast-growing grass used for building and food" },
  { word: "CACTUS", hint: "A spiky desert plant that stores water" },
  { word: "DONKEY", hint: "A domesticated hoofed mammal related to the horse" },
  { word: "FERRIS", hint: "A large upright wheel with passenger cars (amusement ride)" },
  { word: "GONDOLA", hint: "A Venetian boat propelled by a single oar" },
  { word: "HARP", hint: "A large stringed instrument played by plucking" },
  { word: "IVORY", hint: "A hard white material from elephant tusks" },
  { word: "JAGUAR", hint: "A large spotted wild cat from Central and South America" },
  { word: "KALEIDOSCOPE", hint: "A tube with mirrors and colored objects that creates patterns" },
  { word: "LEMONADE", hint: "A drink made from lemons, water, and sugar" },
  { word: "MAGNET", hint: "An object that attracts iron and creates a magnetic field" },
  { word: "NOSTRIL", hint: "One of the two openings in the nose" },
  { word: "ORACLE", hint: "A person or thing regarded as giving wise guidance" },
  { word: "PUMPKIN", hint: "A large orange squash, often carved for Halloween" },
  { word: "RADIATOR", hint: "A device that emits heat to warm a room" },
  { word: "SCORPION", hint: "An arachnid with a venomous stinger on its tail" },
  { word: "TRIANGLE", hint: "A shape with three sides and three angles" },
  { word: "VACCINE", hint: "A substance that provides immunity against a disease" },
  { word: "WHISK", hint: "A kitchen tool used for beating eggs or cream" },
  { word: "ACROBAT", hint: "A performer who does gymnastic feats" },
  { word: "BLENDER", hint: "A kitchen appliance used to mix and puree" },
  { word: "CARNIVAL", hint: "A traveling fair with rides and games" },
  { word: "DUVET", hint: "A soft, flat bag filled with feathers used as a blanket" },
  { word: "EMERALD", hint: "A bright green precious stone" },
  { word: "FLAMINGO", hint: "A tall pink wading bird" },
  { word: "GARGOYLE", hint: "A carved stone creature on a building" },
  { word: "HEDGEHOG", hint: "A small spiny mammal that curls into a ball" },
  { word: "INK", hint: "A colored fluid used for writing or printing" },
  { word: "JET", hint: "A fast aircraft powered by jet engines" }
];
